import { SeverityBadge } from './SeverityBadge';
import { Finding } from '../types/contract';

interface RiskSummaryProps {
  findings: Finding[];
  resolvedCount: number;
  totalFindings: number;
}

export function RiskSummary({ findings, resolvedCount, totalFindings }: RiskSummaryProps) {
  return (
    <div className="bg-white rounded-lg border border-slate-200 p-6">
      <h3 className="text-lg font-semibold text-slate-900 mb-4">
        Risk Summary
      </h3>
      <div className="space-y-3">
        {(['Critical', 'High', 'Medium', 'Low', 'Info'] as const).map(
          (severity) => {
            const count = findings.filter(
              (f) => f.severity === severity
            ).length;
            if (count === 0) return null;
            return (
              <div
                key={severity}
                className="flex items-center justify-between"
              >
                <SeverityBadge severity={severity} />
                <span className="text-sm font-medium text-slate-600">
                  {count}
                </span>
              </div>
            );
          }
        )}
      </div>
      {resolvedCount > 0 && (
        <div className="flex items-center justify-between mt-3 pt-3 border-t border-slate-100">
          <span className="text-sm text-slate-600">Resolved</span>
          <span className="text-sm font-medium text-emerald-600">
            {resolvedCount} of {totalFindings}
          </span>
        </div>
      )}
      <div className="mt-6 pt-6 border-t border-slate-100">
        <p className="text-xs text-slate-400 leading-relaxed">
          This analysis is generated by AI based on standard glazing
          industry contracts. Always verify critical findings with
          legal counsel.
        </p>
      </div>
    </div>
  );
}
